# syntax=docker/dockerfile:1
FROM node:16-alpine
RUN apk update && apk add git
RUN git clone https://github.com/mask-tech/MASK.git --depth 1 --single-branch --branch dev MASK
WORKDIR /MASK
COPY src/member-credentials.json src/credentials.json
RUN npm install
ARG SITE_URL='https://test.kgpmask.club'
CMD ["npm", "run", "dev"]
EXPOSE 6969
